[tool.poetry]
name = "e-motion"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
gradio = "^4.2.0"
transformers = "^4.35.0"
scipy = "^1.11.3"
numpy = "^1.26.1"
torch = "1.12.1"


[tool.poetry.group.dev.dependencies]
pylint = "^3.0.2"
isort = "^5.12.0"
black = "^23.11.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
